//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyMouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_basic_user
    {
        public decimal userid { get; set; }
        public Nullable<decimal> userphone { get; set; }
        public string username { get; set; }
        public string userpwd { get; set; }
        public Nullable<System.DateTime> jointime { get; set; }
        public Nullable<bool> isDel { get; set; }
        public string comment { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
    }
}
