//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyMouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_f_userlogin
    {
        public decimal userid { get; set; }
        public Nullable<System.DateTime> logintime { get; set; }
        public Nullable<System.DateTime> exittime { get; set; }
        public string add_ip { get; set; }
        public string computer { get; set; }
        public string localland { get; set; }
        public Nullable<decimal> temperature { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public string option5 { get; set; }
    }
}
